services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: materiales-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend Spring Boot
  # backend:
  #   build:
  #     context: ./back
  #     dockerfile: Dockerfile
  #   container_name: materiales-backend
  #   environment:
  #     SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  #     DATABASE_URL: ${DATABASE_URL}
  #     DATABASE_USERNAME: ${DATABASE_USERNAME}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #   ports:
  #     - "${BACKEND_PORT}:8080"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

  # # Frontend Angular
  # frontend:
  #   build:
  #     context: ./front
  #     dockerfile: Dockerfile
  #   container_name: materiales-frontend
  #   ports:
  #     - "${FRONTEND_PORT}:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge